services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_db
    # 纯内存，CI 结束即消失
    tmpfs: /var/lib/mysql
    networks:
      ci-net:
        aliases:
          - mysql-container   # 别名，Go 通过这个名字连接 MySQL

    # 不需要 ports:，Go 通过服务名连接

  ceramicraft-user-mservice:
    build:
      context: ../../server
      dockerfile: Dockerfile
    container_name: ceramicraft-user-mservice
    depends_on:
      - mysql
    networks:
      - ci-net
    ports:
      - "8080:8080"   # 只给宿主机（ZAP）用
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: ["sh", "-c", "apt-get update && apt-get install -y netcat-openbsd && chmod +x /app/wait-for.sh && ./wait-for.sh mysql-container 3306 ./main"]
    volumes:
      - ./wait-for.sh:/app/wait-for.sh   # CI 专用配置
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/user-ms/v1/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  ci-net: