services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=user_db
    # Pure memory, disappears when CI ends
    tmpfs: /var/lib/mysql
    networks:
      ci-net:
        aliases:
          - mysql-container   

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: ohAxBaI7QUuIq7lQBYzRYA  
    command: >
      bash -c "
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          kafka-storage format -t $$CLUSTER_ID -c /etc/kafka/kraft/server.properties;
        fi &&
        kafka-server-start /etc/kafka/kraft/server.properties
      "
    networks: 
      ci-net:
        aliases:
          - kafka-container   
  ceramicraft-user-mservice:
    build:
      context: ../../server
      dockerfile: Dockerfile
    container_name: ceramicraft-user-mservice
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_EMAIL_FROM=${SMTP_EMAIL_FROM}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
      - kafka
    networks:
      - ci-net
    ports:
      - "8080:8080"   # 只给宿主机（ZAP）用
    command: ["sh", "-c", "apk add --no-cache netcat-openbsd && chmod +x /app/wait-for.sh && ./wait-for.sh mysql-container 3306 ./main"]
    volumes:
      - ./wait-for.sh:/app/wait-for.sh   # CI 专用配置
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/user-ms/v1/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  ci-net: