name: 功能需求 | Feature Request
description: 用于提出新功能或改进建议 | Propose a new feature or improvement
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## 请按要求填写以下内容 | Please fill out the following information
  - type: textarea
    id: background
    attributes:
      label: 需求背景 | Background
      description: 简要描述为什么需要这个功能或改进 | Briefly describe why this feature or improvement is needed
      placeholder: 需求背景... | Background...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 期望方案 | Expected Solution
      description: 描述你期望的实现方式或效果 | Describe your expected implementation or outcome
      placeholder: 期望方案... | Expected solution...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案 | Alternatives
      description: 如有其他可选方案，可在此补充 | List any alternative solutions or features you've considered
      placeholder: 备选方案... | Alternatives...
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: 其他说明 | Additional Info
      description: 其他补充信息 | Any other information
      placeholder: ...
    validations:
      required: false
